Update JenkinsfileTestTriggerMinorRelease

diff --git a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
--- a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
+++ b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
@@ -82,6 +82,7 @@ pipeline {
         PROMETHEUS_GW_URL = credentials('prometheus-dev-url')
         SERVICE_KEY = credentials('PAGERDUTY_SERVICE_KEY')
         TARGET_UPGRADE_VERSION = "current_branch"
+        TEST_BOOL="true"
     }
 
     stages {
@@ -363,6 +364,34 @@ def getStageOfUpgradeJob(job) {
     return {
         stage("Upgrade Verrazzano from version ${job[0]} to  ${job[1].replace('_', " ")}"){
             script {
+
+                try{
+                    if TEST_BOOL{
+                        echo "Running upgrade job from version current branch to master"
+                        retry(count: JOB_PROMOTION_RETRIES) {
+                            def jobStatus =  build job: "/verrazzano-upgrade-path-tests/${CLEAN_BRANCH_NAME}",
+                            parameters: [
+                                string(name: 'GIT_COMMIT_TO_USE', value: params.GIT_COMMIT_TO_USE),
+                                string(name: 'VERSION_FOR_INSTALL', value: job[1]),
+                                string(name: 'VERSION_FOR_UPGRADE', value: "master"),
+                                string(name: 'VZ_INSTALL_CONFIG', value: params.VZ_INSTALL_CONFIG),
+                                string(name: 'IS_TRIGGERED_MANUALLY', value: "NO"),
+                                string(name: 'VERRAZZANO_OPERATOR_IMAGE', value: params.VERRAZZANO_OPERATOR_IMAGE),
+                                string(name: 'WILDCARD_DNS_DOMAIN', value: params.WILDCARD_DNS_DOMAIN),
+                                string(name: 'TAGGED_TESTS', value: params.TAGGED_TESTS),
+                                string(name: 'INCLUDED_TESTS', value: params.INCLUDED_TESTS),
+                                string(name: 'EXCLUDED_TESTS', value: params.EXCLUDED_TESTS),
+                                string(name: 'CONSOLE_REPO_BRANCH', value: params.CONSOLE_REPO_BRANCH),
+                            ],  wait: true, propagate: true
+                        }
+                        TEST_BOOL="false"
+                    }
+                }catch(err){
+                    catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE'){
+                        echo "Caught: ${err}"
+                        sh "exit 1"
+                    }
+                }
                 try {
                     echo "Running upgrade job from version ${job[0]} to ${job[1].replace('_', " ")}"
                     retry(count: JOB_PROMOTION_RETRIES) {
