created function to run parallel stage for upgrade

diff --git a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
--- a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
+++ b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
@@ -82,7 +82,6 @@ pipeline {
         PROMETHEUS_GW_URL = credentials('prometheus-dev-url')
         SERVICE_KEY = credentials('PAGERDUTY_SERVICE_KEY')
         TARGET_UPGRADE_VERSION = "current_branch"
-        UPGRADE_FROM_CURRENT_TO_MASTER = true
     }
 
     stages {
@@ -196,6 +195,9 @@ pipeline {
                         sleep 5
                     }
                     //parallel upgradeJobsStageMapping
+
+                    // running the upgrade from current to master in parallel with the other upgrade jobs
+                    upgradeFromCurrentBranchToMaster()
                      }
                    }
                 }
@@ -362,38 +364,6 @@ List extractReleaseTags(final String fileContent) {
 
 def getStageOfUpgradeJob(job) {
     return {
-        if (UPGRADE_FROM_CURRENT_TO_MASTER){
-            stage("Upgrade Verrazzano from version ${TARGET_UPGRADE_VERSION} to master"){
-                script{
-                    try{
-                            echo "Running upgrade job from version current branch to master"
-                            retry(count: JOB_PROMOTION_RETRIES) {
-                                def jobStatus =  build job: "/verrazzano-upgrade-path-tests/${CLEAN_BRANCH_NAME}",
-                                parameters: [
-                                    string(name: 'GIT_COMMIT_TO_USE', value: params.GIT_COMMIT_TO_USE),
-                                    string(name: 'VERSION_FOR_INSTALL', value: job[1] ),
-                                    string(name: 'VERSION_FOR_UPGRADE', value: "master"),
-                                    string(name: 'VZ_INSTALL_CONFIG', value: params.VZ_INSTALL_CONFIG),
-                                    string(name: 'IS_TRIGGERED_MANUALLY', value: "NO"),
-                                    string(name: 'VERRAZZANO_OPERATOR_IMAGE', value: params.VERRAZZANO_OPERATOR_IMAGE),
-                                    string(name: 'WILDCARD_DNS_DOMAIN', value: params.WILDCARD_DNS_DOMAIN),
-                                    string(name: 'TAGGED_TESTS', value: params.TAGGED_TESTS),
-                                    string(name: 'INCLUDED_TESTS', value: params.INCLUDED_TESTS),
-                                    string(name: 'EXCLUDED_TESTS', value: params.EXCLUDED_TESTS),
-                                    string(name: 'CONSOLE_REPO_BRANCH', value: params.CONSOLE_REPO_BRANCH),
-                                ],  wait: true, propagate: true
-                            }
-                        UPGRADE_FROM_CURRENT_TO_MASTER = false
-                    }catch(err){
-                        catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE'){
-                            echo "Caught: ${err}"
-                            sh "exit 1"
-                        }
-                    }
-
-                }
-            }
-        }
         stage("Upgrade Verrazzano from version ${job[0]} to  ${job[1].replace('_', " ")}"){
             script {
                 try {
@@ -422,5 +392,39 @@ def getStageOfUpgradeJob(job) {
                 }
             }
         }
+    }
+}
+
+def upgradeFromCurrentBranchToMaster(){
+    return {
+        stage("Upgrade Verrazzano from version ${TARGET_UPGRADE_VERSION} to master"){
+            script{
+                try{
+                    echo "Running upgrade job from version current branch to master"
+                    retry(count: JOB_PROMOTION_RETRIES) {
+                        def jobStatus =  build job: "/verrazzano-upgrade-path-tests/${CLEAN_BRANCH_NAME}",
+                        parameters: [
+                                    string(name: 'GIT_COMMIT_TO_USE', value: params.GIT_COMMIT_TO_USE),
+                                    string(name: 'VERSION_FOR_INSTALL', value: ${TARGET_UPGRADE_VERSION} ),
+                                    string(name: 'VERSION_FOR_UPGRADE', value: "master"),
+                                    string(name: 'VZ_INSTALL_CONFIG', value: params.VZ_INSTALL_CONFIG),
+                                    string(name: 'IS_TRIGGERED_MANUALLY', value: "NO"),
+                                    string(name: 'VERRAZZANO_OPERATOR_IMAGE', value: params.VERRAZZANO_OPERATOR_IMAGE),
+                                    string(name: 'WILDCARD_DNS_DOMAIN', value: params.WILDCARD_DNS_DOMAIN),
+                                    string(name: 'TAGGED_TESTS', value: params.TAGGED_TESTS),
+                                    string(name: 'INCLUDED_TESTS', value: params.INCLUDED_TESTS),
+                                    string(name: 'EXCLUDED_TESTS', value: params.EXCLUDED_TESTS),
+                                    string(name: 'CONSOLE_REPO_BRANCH', value: params.CONSOLE_REPO_BRANCH),
+                                ],  wait: true, propagate: true
+                            }
+                    }catch(err){
+                        catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE'){
+                            echo "Caught: ${err}"
+                            sh "exit 1"
+                        }
+                    }
+
+                }
+            }
     }
 }
